#!/bin/bash

FAILURES=0

if [ "$1" != "" ]; then
  export BIN_DIR=`readlink -f $1`
  if [ -L tests/niedoida/niedoida ]; then
    rm tests/niedoida/niedoida
  fi
  ln -s $BIN_DIR tests/niedoida/niedoida || exit 1
fi

cd tests/niedoida

if [ -x niedoida ]; then
  echo "niedoida"
  python3 run_all_methods_tests.py
  if [ $? -ne 0 ]; then
    FAILURES=$(expr $FAILURES + 1)
  fi
else 
  exit 1
fi

cd ../..

echo
echo
echo Summary:

if [ $FAILURES -ne 0 ]; then
  echo "FAILED: (failures=$FAILURES)"
else
  echo OK
fi

exit $FAILURES
