/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "gto_kit/gto_utils.hpp"

namespace {
    /* matrices for transformation to spherical
       rows numbered by m (-l->l)
       (for p: px, py, pz),
       columns by {lx,ly,lz}
    */

    using std::sqrt;

    // l == 0
    static const double t0[1][1] = {{1}};

    // l == 1 (100, 010, 001)
    static const double t1[3][3] = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}};

    // l == 2 (200, 110, 101, 020, 011, 002)
    static const double t2[5][6] = {
        {0, sqrt(3.0), 0, 0, 0, 0},
        {0, 0, 0, 0, sqrt(3.0), 0},
        {-0.5, 0, 0, -0.5, 0, 1},
        {0, 0, sqrt(3.0), 0, 0, 0},
        {sqrt(3.0) / 2.0, 0, 0, -sqrt(3.0) / 2.0, 0, 0}};

    // l == 3 (300, 210, 201, 120, 111, 102, 030, 021, 012, 003)
    static const double t3[7][10] = {
        {0,
         3 * sqrt(15.0) / sqrt(24.0),
         0,
         0,
         0,
         0,
         -sqrt(15.0) / sqrt(24.0),
         0,
         0,
         0},
        {0, 0, 0, 0, sqrt(15.0), 0, 0, 0, 0, 0},
        {0,
         -sqrt(15.0) / sqrt(40.0),
         0,
         0,
         0,
         0,
         -sqrt(15.0) / sqrt(40.0),
         0,
         4 * sqrt(15.0) / sqrt(40.0),
         0},
        {0,
         0,
         -3 * sqrt(15.0) / sqrt(60.0),
         0,
         0,
         0,
         0,
         -3 * sqrt(15.0) / sqrt(60.0),
         0,
         2 * sqrt(15.0) / sqrt(60.0)},
        {-sqrt(15.0) / sqrt(40.0),
         0,
         0,
         -sqrt(15.0) / sqrt(40.0),
         0,
         4 * sqrt(15.0) / sqrt(40.0),
         0,
         0,
         0,
         0},
        {0, 0, sqrt(15.0) / 2.0, 0, 0, 0, 0, -sqrt(15.0) / 2.0, 0, 0},
        {sqrt(15.0) / sqrt(24.0),
         0,
         0,
         -3 * sqrt(15.0) / sqrt(24.0),
         0,
         0,
         0,
         0,
         0,
         0}};

    static const double t4[9][15] = {{0,
                                      sqrt(105.0) / sqrt(12.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      -sqrt(105.0) / sqrt(12.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0},
                                     {0,
                                      0,
                                      0,
                                      0,
                                      3 * sqrt(105.0) / sqrt(24.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      -sqrt(105.0) / sqrt(24.0),
                                      0,
                                      0,
                                      0},
                                     {0,
                                      -sqrt(105.0) / sqrt(84.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      -sqrt(105.0) / sqrt(84.0),
                                      0,
                                      6 * sqrt(105.0) / sqrt(84.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0},
                                     {0,
                                      0,
                                      0,
                                      0,
                                      -3 * sqrt(105.0) / sqrt(168.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      -sqrt(105.0) / sqrt(168.0),
                                      0,
                                      4 * sqrt(105.0) / sqrt(168.0),
                                      0},
                                     {3 * sqrt(105.0) / sqrt(6720.0),
                                      0,
                                      0,
                                      6 * sqrt(105.0) / sqrt(6720.0),
                                      0,
                                      -24 * sqrt(105.0) / sqrt(6720.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      3 * sqrt(105.0) / sqrt(6720.0),
                                      0,
                                      -24 * sqrt(105.0) / sqrt(6720.0),
                                      0,
                                      8 * sqrt(105.0) / sqrt(6720.0)},
                                     {0,
                                      0,
                                      -3 * sqrt(105.0) / sqrt(168.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      -3 * sqrt(105.0) / sqrt(168.0),
                                      0,
                                      4 * sqrt(105.0) / sqrt(168.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0},
                                     {-sqrt(105.0) / sqrt(336.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      6 * sqrt(105.0) / sqrt(336.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      sqrt(105.0) / sqrt(336.0),
                                      0,
                                      -6 * sqrt(105.0) / sqrt(336.0),
                                      0,
                                      0},
                                     {0,
                                      0,
                                      sqrt(105.0) / sqrt(24.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      -sqrt(105.0) / sqrt(24.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0},
                                     {sqrt(105.0) / sqrt(192.0),
                                      0,
                                      0,
                                      -6 * sqrt(105.0) / sqrt(192.0),
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      0,
                                      sqrt(105.0) / sqrt(192.0),
                                      0,
                                      0,
                                      0,
                                      0}};

    template <std::size_t M, std::size_t N>
    arma::mat make_matrix(const double (&array)[M][N])
    {
        arma::mat m(M, N);
        for (unsigned k = 0; k < M; ++k)
            for (unsigned l = 0; l < N; ++l)
                m(k, l) = array[k][l];
        return m;
    }
}

namespace niedoida {
    namespace gto {
        const arma::mat cartesian_to_spherical[] = {make_matrix(t0),
                                                    make_matrix(t1),
                                                    make_matrix(t2),
                                                    make_matrix(t3),
                                                    make_matrix(t4)};
    }
}
