/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include <boost/test/floating_point_comparison.hpp>
#include <boost/test/test_tools.hpp>    
#include <boost/test/unit_test.hpp>

#include "xc_kit/xc_functionals.hpp"
    
void check_slater_x_functional()
{
    const double eps = 1e-7;
    XCFunctionalData xc;
    xc = slater_x_functional(0.17E+01, 0.17E+01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.377592720836E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.148075576798E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.148075576798E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.290344268232E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.290344268232E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.17E+01, 0.17E+01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.377592720836E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.148075576798E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.148075576798E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.290344268232E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.290344268232E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.15E+01, 0.15E+01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.319555819038E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.142024808461E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.142024808461E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.315610685470E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.315610685470E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.88E-01, 0.88E-01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.728453690414E-01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.551858856374E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.551858856374E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.209037445596E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.209037445596E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.18E+04, 0.18E+04, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.407494475320E+05, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.150923879748E+02, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.150923879748E+02, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.279488666200E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.279488666200E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.18E+04, 0.18E+04, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.407494475320E+05, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.150923879748E+02, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.150923879748E+02, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.279488666200E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.279488666200E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.16E+04, 0.16E+04, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.348271841145E+05, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.145113267144E+02, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.145113267144E+02, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.302319306550E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.302319306550E-02, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.26E+00, 0.26E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.308832394647E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.791877934993E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.791877934993E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.101522812179E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.101522812179E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.53E+05, 0.53E+05, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.370503980143E+07, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.466042742318E+02, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.466042742318E+02, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.293108642967E-03, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.293108642967E-03, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.47E+05, 0.47E+05, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.315661921284E+07, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.447747406077E+02, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.447747406077E+02, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.317551351828E-03, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.317551351828E-03, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.15E+00, 0.15E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.148324672136E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.659220765051E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.659220765051E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.146493503345E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.146493503345E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.35E+01, 0.00E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.494484233083E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.188374945936E+01, eps);
    BOOST_CHECK_SMALL(xc.de_drb, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.179404710416E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbrb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.35E+01, 0.00E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.494484233083E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.188374945936E+01, eps);
    BOOST_CHECK_SMALL(xc.de_drb, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.179404710416E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbrb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.30E+01, 0.00E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.402615103023E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.178940045788E+01, eps);
    BOOST_CHECK_SMALL(xc.de_drb, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.198822273098E+00, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbrb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.58E-01, 0.00E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.208913119508E-01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.480260044845E+00, eps);
    BOOST_CHECK_SMALL(xc.de_drb, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.276011520026E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbrb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.82E+02, 0.81E+02, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.657615683804E+03, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.539020244480E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.536820137364E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.219113920520E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.220913636775E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.39E+02, 0.38E+02, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.241948147838E+03, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.420747936684E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.417120618800E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.359613621097E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.365895279649E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.13E+00, 0.95E-01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.101616142698E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.628513933519E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.566119777958E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.161157418851E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.198638518582E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.78E-01, 0.31E-01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.400731073431E-01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.530109182127E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.389751405963E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.226542385525E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.419087533293E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.50E+02, 0.49E+02, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.338253135027E+03, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.457078149734E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.454010418713E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.304718766489E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.308850624975E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.40E+02, 0.40E+02, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.254588260307E+03, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.424313767179E+01, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.424313767179E+01, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.353594805982E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.353594805982E-01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.12E+00, 0.10E+00, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.982681500273E-01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.611966348389E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.575882382297E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.169990652330E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.191960794099E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
    xc = slater_x_functional(0.48E-01, 0.25E-01, 2);
    BOOST_CHECK_CLOSE(xc.e, -0.230346081831E-01, eps);
    BOOST_CHECK_CLOSE(xc.de_dra, -0.450900660715E+00, eps);
    BOOST_CHECK_CLOSE(xc.de_drb, -0.362783167860E+00, eps);
    BOOST_CHECK_SMALL(xc.de_dgaa, eps);
    BOOST_CHECK_SMALL(xc.de_dgab, eps);
    BOOST_CHECK_SMALL(xc.de_dgbb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drara, -0.313125458830E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_drarb, eps);
    BOOST_CHECK_CLOSE(xc.d2e_drbrb, -0.483710890480E+01, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dragbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_drbgbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagaa, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgaagbb, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgabgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgab, eps);
    BOOST_CHECK_SMALL(xc.d2e_dgbbgbb, eps);
}
